---
- name: update apt-packages
  apt: "upgrade=dist update_cache=yes"
  become: yes
  become_method: sudo

- name: install java by apt-get
  apt:
    name: openjdk-8-jre-headless
    force: yes
  become: yes
  become_method: sudo

- name: add the repository key to the system
  shell: "wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -" 

- name: append the Debian package repository address to the server's source.list
  shell: "echo deb http://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list"

- name: install jenkins by apt-get
  apt:
    name: jenkins
    force: yes
  become: yes
  become_method: sudo